name: Deploy
on:
  push:
    branches:
      - main # 只在main上push触发部署
    #   - README.md
    #   - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - name: Checkout
        uses: actions/checkout@v2 # Download Repo
      - run: yarn install
      - run: yarn build

      #  Caitouyun Deploy
      - name: Caitou Deploy
        run: |
          curl -sf https://cli.caitouyun.com/install.sh | sh
          caitou deploy --git
        env:
          CAITOU_TOKEN: ${{ secrets.CAITOU_TOKEN }}
##
